server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  servlet:
    context-path: /nova/v1
spring:
  jackson:
    time-zone: America/Mexico_City
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/nova?useSSL=false
    username: root
    password: exon1704
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: nova
    show-sql: true
  application:
    name: nova
  main:
    lazy-initialization: true
